[project]
name = "autopipe"
version = "0.0.1"
readme = "README.md"

[project.optional-dependencies]
dev = [
    "black",
    "isort",
    "pytest",
    "coverage",
    "pre-commit",
]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"